### ISSUE TITLE
 A&D blood pressure monitor problem

### ISSUE THREAD

**Issue by mariaCP** [andengineering/A-D-HDP-Android-Demo#1]
Hello, I am trying to use this application with an A&D device (blood pressure monitor, model UA-767PBT) but the connection state doesn't change from disconnect to connect. This is the log:

I/ActivityManager(  388): Start proc com.example.bluetooth.health for service com.example.bluetooth.health/.BluetoothHDPService: pid=24176 uid=10106 gids={50106, 3002, 3001, 1028}
D/dalvikvm(24176): Late-enabling CheckJNI
D/BluetoothHDPService(24176): onCreate
D/BluetoothManagerService(  388): Message: 20
D/BluetoothManagerService(  388): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@429118b8:true
D/BluetoothManagerService(  388): Message: 30
D/BluetoothHealth(24176): Proxy object connected
D/BluetoothHDPService(24176): onServiceConnected
I/ActivityManager(  388): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.example.bluetooth.health/.BluetoothHDPActivity} from pid 627
D/BluetoothHealthActivity(24176): onCreate
D/dalvikvm(24176): GC_FOR_ALLOC freed 46K, 1% free 9089K/9172K, paused 16ms, total 16ms
I/dalvikvm-heap(24176): Grow heap (frag case) to 12.962MB for 4250360-byte allocation
D/dalvikvm(24176): GC_FOR_ALLOC freed 1K, 1% free 13238K/13324K, paused 20ms, total 20ms
D/dalvikvm(24176): GC_FOR_ALLOC freed <1K, 1% free 13239K/13324K, paused 11ms, total 11ms
I/dalvikvm-heap(24176): Grow heap (frag case) to 17.015MB for 4250360-byte allocation
D/dalvikvm(24176): GC_FOR_ALLOC freed <1K, 1% free 17389K/17476K, paused 19ms, total 19ms
D/BluetoothHealthActivity(24176): onStart
D/BluetoothHealthActivity(24176): initialize
D/BluetoothHDPService(24176): BluetoothHDPService is running.
D/BluetoothHDPService(24176): onBind
D/libEGL  (24176): loaded /vendor/lib/egl/libEGL_POWERVR_SGX540_120.so
D/libEGL  (24176): loaded /vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so
D/libEGL  (24176): loaded /vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so
D/OpenGLRenderer(24176): Enabling debug mode 0
D/BluetoothHealthActivity(24176): onServiceConnected
D/BluetoothHDPService(24176): handleMessage: 200
D/BluetoothHDPService(24176): Activity client registered
I/ActivityManager(  388): Displayed com.example.bluetooth.health/.BluetoothHDPActivity: +1s169ms

When I press the Register button:
D/BluetoothHealthActivity(24176): sendMessage
D/BluetoothHDPService(24176): handleMessage: 300
D/BluetoothHDPService(24176): registerApp
D/HealthService(23820): HealthService Handler msg: 1
D/BluetoothHDPService(24176): onHealthAppConfigurationStatusChange
D/BluetoothHDPService(24176): sendMessage
D/BluetoothHealthActivity(24176): handleMessage
D/HealthService(23820): HealthService Handler msg: 11
D/BluetoothHDPService(24176): onHealthAppConfigurationStatusChange
D/BluetoothHDPService(24176): sendMessage
D/BluetoothHealthActivity(24176): handleMessage

Finally, when the device provides the blood pressure measurement: 

W/bt-btif (23820): info:x10
D/        (23820): remote version info [xx:xx:xx:xx:xx:xx]: 4, a, 14f0
D/btif_config_util(23820): btif_config_save_file(L153): in file name:/data/misc/bluedroid/bt_config.new
D/BluetoothManagerService(  388): Message: 20
D/BluetoothManagerService(  388): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@4240afb8:true
I/BluetoothConnectionReceiver(23198): onReceive(context, Intent { act=android.bluetooth.device.action.ACL_CONNECTED flg=0x8000010 cmp=com.google.android.googlequicksearchbox/com.google.android.search.core.service.BluetoothConnectionReceiver (has extras) }, xx:xx:xx:xx:xx:xx)
E/bt-btm  (23820): btm_sec_disconnected - Clearing Pending flag
I/BluetoothConnectionReceiver(23198): onReceive(context, Intent { act=android.bluetooth.device.action.ACL_DISCONNECTED flg=0x8000010 cmp=com.google.android.googlequicksearchbox/com.google.android.search.core.service.BluetoothConnectionReceiver (has extras) }, xx:xx:xx:xx:xx:xx)
D/LightsService(  388): Excessive delay setting light: 67ms
D/BluetoothDiscoverableTimeoutReceiver(23323): Disable discoverable...
I/BluetoothAdapterProperties(23820): adapterPropertyChangedCallback with type:9 len:4
D/BluetoothAdapterProperties(23820): Discoverable Timeout:120
I/BluetoothAdapterProperties(23820): adapterPropertyChangedCallback with type:7 len:4
D/BluetoothAdapterProperties(23820): Scan Mode:21

I use Android 4.3. Can you help me to understand the problem? Thank you.

**Comment by santhoshselvam** [comment]
I'm trying to get data from BP monitor while receiving data will be so what is the error

**Comment by santhoshselvam** [comment]
I'm trying to get data from BP monitor while receiving function will be delay so what is error but in my side Bluetooth HDP services is running and also services created so what is the error any one can help me. Advance thank you.

**Comment by vidyajejurkar** [comment]
I m trying to ru n this app..app runs properly but it shows weight of user 0.0 kg
why it happens??

**Comment by nunoar** [comment]
This app is for the blood pressure, not the weight scale.

**Comment by vidyajejurkar** [comment]
Did U know about weight scale??/can u help me in weight scale case???

**Comment by thejae** [comment]
@vidyajejurkar is this the machine you have?
![and_ua767pbtc](https://cloud.githubusercontent.com/assets/738694/14422891/8da2fad2-000b-11e6-98e9-cbeb641e9f6b.jpg)

**Comment by nunoar** [comment]
This app is for the blood pressure, not the weight scale. 

I am wondering if you have the scale set to Kg?

**Comment by nunoar** [comment]
@vidyajejurkar, i am wondering, do you have your weight scale set to Kg?

**Comment by vidyajejurkar** [comment]
no actually i comment on wrong post.actually i m trying for weight scale.

**Comment by vidyajejurkar** [comment]
i got output for weight scale like below screen

**Comment by vidyajejurkar** [comment]
if (data[0] != (byte) 0x00) {
                        String test = byte2hex(data);
                        if (data[0] == (byte) 0xE2) {
                            // data_AR
                            count = 1;
                            (new WriteThread(mFd)).start();
                            try {
                                sleep(100);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                            count = 2;
                            (new WriteThread(mFd)).start();
                        } else if (data[0] == (byte) 0xE7) {

```
                        // work for legacy device...
                        if (data[18] == (byte) 0x12
                                && data[19] == (byte) 0x1e) // fixed report
                        {
                            count = 3;
                            // set invoke id so get correct response
                            invoke = new byte[] { data[6], data[7] };
                            // write back response
                            (new WriteThread(mFd)).start();

                            // parse data!!

                            if (data[3] == (byte) 0x3a) {
                                // Log.i("EXCEL", excel);

                                String pr = test.substring(84, 88);
                                Log.i("PARSING weight :", "" + pr);
                                int weight = Integer.parseInt(pr, 16);

                                Log.i("PARSING weight :", "" + weight);
                                sendMessage(RECEIVED_SYS, weight);
                            }

                        } else {
                            count = 2;
                        }
                    } else if (data[0] == (byte) 0xE4) {
                        count = 4;
                        (new WriteThread(mFd)).start();
                        // sendMessage();
                    }
                    // zero out the data
                    for (int i = 0; i < data.length; i++) {
                        data[i] = (byte) 0x00;
                    }
                }
                sendMessage(STATUS_READ_DATA, 0);
            }
        } catch (IOException ioe) {
        }
        if (mFd != null) {
            try {
                mFd.close();
            } catch (IOException e) { /* Do nothing. */
            }
        }
        sendMessage(STATUS_READ_DATA_DONE, 0);
    }
}

private class WriteThread extends Thread {
    private ParcelFileDescriptor mFd;

    public WriteThread(ParcelFileDescriptor fd) {
        super();
        mFd = fd;
    }

    public byte[] getBluetoothMacAddress() {
        BluetoothAdapter mBluetoothAdapter = BluetoothAdapter
                .getDefaultAdapter();

        // if device does not support Bluetooth
        if (mBluetoothAdapter == null) {
            Log.d(TAG, "device does not support bluetooth");
            return null;
        }

        String[] mac = mBluetoothAdapter.getAddress().split(":");
        byte[] macAddress = new byte[mac.length];

        for (int i = 0; i < mac.length; i++) {
            Integer hex = Integer.parseInt(mac[i], 16);
            macAddress[i] = hex.byteValue();
        }

        return macAddress;
    }

    @Override
    public void run() {
        FileOutputStream fos = new FileOutputStream(mFd.getFileDescriptor());
        // FileInputStream fis = new
        // FileInputStream(mFd.getFileDescriptor());
        // Association Response [0xE300]

        byte[] macAddress = getBluetoothMacAddress();

        final byte data_AR[] = new byte[] { (byte) 0xE3, (byte) 0x00,
                (byte) 0x00, (byte) 0x2C, 
                (byte) 0x00, (byte) 0x00,
                (byte) 0x50, (byte) 0x79, 
                (byte) 0x00, (byte) 0x26,
                (byte) 0x80, (byte) 0x00, (byte) 0x00, (byte) 0x00,
                (byte) 0x80, (byte) 0x00, 
                (byte) 0x80, (byte) 0x00,(byte) 0x00, (byte) 0x00,
                (byte) 0x00,(byte) 0x00,(byte) 0x00,(byte) 0x00,
                (byte) 0x80,(byte) 0x00,(byte) 0x00,(byte) 0x00,
                (byte) 0x00,(byte) 0x08, 
                macAddress[0], macAddress[1], macAddress[2], (byte) 0xFF,
                (byte) 0xFE, macAddress[3], macAddress[4], macAddress[5],
                (byte)0x88, (byte)0x77,(byte) 0x66, (byte)0x55, (byte)0x44,(byte)0x33, (byte)0x22, (byte)0x11,
                (byte)0x00, (byte)0x00,
                (byte)0x00, (byte)0x00,
                (byte)0x00, (byte)0x00, 
                (byte)0x00, (byte)0x00, (byte)0x00, (byte)0x00};




        // Presentation APDU [0xE700]
        final byte data_DR[] = new byte[] { (byte) 0xE7, (byte) 0x00,
                (byte) 0x00, (byte) 0x12, (byte) 0x00, (byte) 0x10,
                (byte) invoke[0], (byte) invoke[1], (byte) 0x02,
                (byte) 0x01, (byte) 0x00, (byte) 0x0A, (byte) 0x00,
                (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00,
                (byte) 0x00, (byte) 0x0D, (byte) 0x1D, (byte) 0x00,
                (byte) 0x00 };

        final byte get_MDS[] = new byte[] { (byte) 0xE7, (byte) 0x00,
                (byte) 0x00, (byte) 0x0E, (byte) 0x00, (byte) 0x0C,
                (byte) 0x12, (byte) 0x34, (byte) 0x01, (byte) 0x03,
                (byte) 0x00, (byte) 0x06, (byte) 0x00, (byte) 0x00,
                (byte) 0x00, (byte) 0x00, (byte) 0x00, (byte) 0x00 };

        final byte data_RR[] = new byte[] { (byte) 0xE5, (byte) 0x00,
                (byte) 0x00, (byte) 0x02, (byte) 0x00, (byte) 0x00 };
        try {
            Log.i(TAG, String.valueOf(count));
            if (count == 1) {
                fos.write(data_AR);
                Log.i(TAG, "Association Responsed!");
            } else if (count == 2) {
                fos.write(get_MDS);
                Log.i(TAG, "Get MDS object attributes!");
                // fos.write(data_ABORT);
            } else if (count == 3) {
                fos.write(data_DR);
                Log.i(TAG, "Data Responsed!");
            } else if (count == 4) {
                fos.write(data_RR);
                Log.i(TAG, "Data Released!");
            }

            fos.close();
        } catch (IOException ioe) {
        }
    }
}
```

is decoding of data of every weight scale is same??? 
i am using "A & D medical UC-351PBT-Ci"

**Comment by vidyajejurkar** [comment]
@Nuno Rebelo :
did u worked on  BLE Weightscale??????????

**Comment by nunoar** [comment]
No, I haven't.
I was not using that model, probably that's why the code doesn't work.
Without help from A&D you'll have get the hexadecimal you get and match it with the specification from Continua alliance to identify where the values are.

**Comment by vidyajejurkar** [comment]
No , I get weight now using UC-351.now i want to do same thing using ble
UC-352 weightscale .

**Comment by thejae** [comment]
@vidyajejurkar Hi man, i know you are frustrated with the SDK/ API of A&D, but you got to stop hijacking people's thread with off topic problems. Please [create a new issue](https://github.com/andengineering/A-D-HDP-Android-Demo/issues/new).

**Comment by asinisalo** [comment]
Hi Guys,

This is a 2 years old problem, and there is no remedy.

The problem is Google damaged the MDP stack (medical device protocoll) in their Bluetooth 3. 

You can fix it by rooting the phone, but that certainly is not a generic solution.

-- if you see some older device working with BT 3.0 it either uses serial or COMM protocoll (and they are not even near Continua).

What works are NEW scales, BP meters e.a. with BTLE (alias Smart BT, BT 4.0) - BTLE on the other hand means brand new phones.

> > anyway these are recommended for programming anything new to the market

Cheers,
Ari
